title: EE-EMERGE WEBSITE TEMPLATE
tagline: EE-EMERGE WEBSITE TAGLINE
show_downloads: true
remote_theme: tuur29/pages-themes-cayman
hide_first_title: false # Useful if README.md is used on both github and pages
color:
  header: "#FFFFFF"
  gradient_left: "#00e0ff"
  gradient_right: "#51024b"
  section_title: "#000000" # this default to gradient_color
  link: "#000000"
